--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/BossAnnouncement
branches:
- master
projects:
  BossAnnouncement:
    path: ""
    libs:
      - src: xenialdan/bossbarapi/bossbarapi
        version: ^5.0.0
...
