  name: BossAnnouncement
  main: xenialdan\BossAnnouncement\Main
  version: 1.1.2
  api: [2.0.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
  load: POSTWORLD
  authors: [XenialDan]
  depend: BossBarAPI
